### ISSUE TITLE
Missing UI

### ISSUE THREAD

**Issue by Bigmack73** [Sirillion/SMXui#2]
Not sure how or why not working. I have updated to the new version of the UI. Still not getting the skills menu like in the screenshots. Its still the default.

Is there something I am missing or doing wrong?

btw. awesome mod

**Comment by Sirillion** [comment]
How do you update? Manual download and install or mod launcher?

**Comment by Bigmack73** [comment]
I manually download the zip file and unzip it into the mods folder.

**Comment by Sirillion** [comment]
Well, then it should work. Have you checked to see that it has been correctly installed? Try removing the old version first, then install again and see if that makes a difference.

**Comment by Bigmack73** [comment]
I just removed the mod, and redownloaded and installed it. Now it works, thanks.

Really like the middle feature when moving from inventory to a storage box, click on it, it moves what ever is that box to it. Makes it a whole lot easier sorting.

**Comment by Sirillion** [comment]
Glad to hear you got it working. Issue closed :)
